### ISSUE TITLE
Running library leaves lots of temporary directories

### ISSUE THREAD

**Issue by nkrot** [Kensuke-Mitsuzawa/DocumentFeatureSelection#34]
I have been learning how to use this library (have certain interest in Binormal Separation) and when running tests with the command:

    pyhton3 setup.py test

I noticed that there are lots of tmp directories created that are **not deleted** afterwards. Would it be possible to implement automatic cleanup in the library itself?

I am using Python 3.4.2

**Comment by Kensuke-Mitsuzawa** [comment]
@nkrot Thanks for your making the issue. Yes, as you say, this package creates usually tmp files because the amounts of data(matrix size) sometimes give pressure to memory.
And, as you say, the package __does not delete__ tmp files. This is kind of my bad. Still, the tmp files are created in `/tmp` directory. Therefore, I believe, OS deletes tmp files automatically some day.

Hm...I should delete tmp files. Thanks! I do it in next version.

**Comment by Kensuke-Mitsuzawa** [comment]
put these line. Tmp files are deleted after computation.
https://github.com/Kensuke-Mitsuzawa/DocumentFeatureSelection/blob/master/DocumentFeatureSelection/interface.py#L158-L160

**Comment by nkrot** [comment]
Hi @Kensuke-Mitsuzawa,
Thanks for quick reaction! The fix however solves the problem partially. I added another issue, #38.
